services:
  # 1. Laravel Uygulama Motorumuz
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - shortify_network

  # 2. Arka Plan İşçimiz (Kuyruk Yönetimi için)
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan queue:work
    depends_on:
      - app
      - redis
    networks:
      - shortify_network

  # 3. MySQL 8.0 Veritabanımız
  db:
    image: mysql:8.0
    container_name: url_shortener_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shortify_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: shortify_user
      MYSQL_PASSWORD: shortify_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shortify_network

  # 4. Hızlı Önbellek & Tıklama Sayacı (Redis)
  redis:
    image: redis:alpine
    container_name: url_shortener_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - shortify_network

networks:
  shortify_network:
    driver: bridge

volumes:
  dbdata:
    driver: local